prova_a=float(input("Digite a nota na prova 1: "))
prova_b= float(input("Digite a nota na prova 2: "))
prova_c= float(input("Digite a nota na prova 3: "))
nome_aluno=input("Digite seu nome: ")
media=  3/(1/prova_a+1/prova_b+1/prova_c)
print(f"Sua média è: {media:2f}")
print(f"Seu nome è: {nome_aluno}")